import assert from 'node:assert/strict';
import JSZip from 'jszip';
import { migrateToV4 } from '../../src/v4/migrations.js';
import { createDocumentSet, createExportBundle, createIdeWorkspaceFiles, createIdeWorkspacePackage, createPromtgenPackage, exportCanonicalMarkdown, readPromtgenPackage, resolveCanonicalRevision } from '../../src/v4/exporter.js';
import { redactSensitiveText } from '../../src/v4/ai-context.js';

const legacy = { id: 'legacy-1', schemaVersion: 3, name: 'Eski Plan', stepDepth: 5, workflowStage: 'EXPORTED', draftDescription: 'Bir yerel not uygulaması', tasks: [{ title: 'Editörü oluştur' }] };
const result = migrateToV4(legacy);
assert.equal(result.success, true);
assert.deepEqual(result.backup, legacy);
assert.equal(result.project.lifecycle.status, 'finalized');
assert.equal(result.project.lifecycle.activePhase, 'READY');
assert.equal(result.project.exports.length, 1);
assert.equal(result.project.metadata.canonicalModelVersion, 1);
assert.equal(result.project.tasks[0].id, 'task-1');
const docs = createDocumentSet(result.project);
assert.ok(docs['agents/codex.md'].includes('Bir yerel not uygulaması'));
assert.ok(docs['documents/prd.md']);
assert.ok(exportCanonicalMarkdown(result.project).includes('Editörü oluştur'));
const bundle = await createExportBundle(result.project, { adapters: ['codex'] });
assert.equal(bundle.canonicalHash.length, 64);
assert.deepEqual(bundle.record.adapterIds, ['codex']);
assert.equal(bundle.record.revision, result.project.revision);
const packaged = await createPromtgenPackage(result.project, { adapters: ['codex'] });
assert.equal(packaged.manifest.formatVersion, 2);
const imported = await readPromtgenPackage(packaged.blob);
assert.equal(imported.id, result.project.id);
assert.equal(resolveCanonicalRevision(imported, imported.revision).revision, imported.revision);
const ideFiles = createIdeWorkspaceFiles(result.project, { adapters: ['codex', 'cursor', 'claude'] });
assert.ok(ideFiles.files['AGENTS.md'].includes(`canonical plan **r${result.project.revision}**`));
assert.ok(ideFiles.files['.cursor/rules/promtgen-plan.mdc'].includes('alwaysApply: true'));
assert.ok(ideFiles.files['CLAUDE.md'].includes('Zorunlu rol sırası'));
assert.equal(JSON.parse(ideFiles.files['.promtgen/execution.json']).sourceRevision, result.project.revision);
assert.throws(() => createIdeWorkspaceFiles(result.project, { adapters: ['unknown'] }), /En az bir IDE/);
const idePackage = await createIdeWorkspacePackage(result.project, { adapters: ['codex', 'cursor'] });
assert.equal(idePackage.manifest.format, 'promtgen-ide-workspace');
assert.equal(idePackage.manifest.canonicalHash.length, 64);
assert.deepEqual(idePackage.record.adapterIds, ['codex', 'cursor']);
const ideZip = await JSZip.loadAsync(await idePackage.blob.arrayBuffer());
assert.ok(ideZip.file('AGENTS.md'));
assert.ok(ideZip.file('.cursor/rules/promtgen-plan.mdc'));
assert.equal(JSON.parse(await ideZip.file('.promtgen/manifest.json').async('string')).sourceRevision, result.project.revision);

async function maliciousPackage(projectJson, extras = [], compression = 'DEFLATE') {
    const zip = new JSZip();
    zip.file('manifest.json', JSON.stringify({ format: 'promtgen', formatVersion: 1, schemaVersion: 4, files: [] }));
    zip.file('project.json', projectJson);
    for (const [name, content] of extras) zip.file(name, content);
    return zip.generateAsync({ type: 'uint8array', compression });
}

const pollutedJson = JSON.stringify(result.project).replace(/^\{/, '{"__proto__":{"polluted":true},');
await assert.rejects(readPromtgenPackage(await maliciousPackage(pollutedJson)), /yasak anahtar/);
const tooManyEntries = Array.from({ length: 499 }, (_, index) => [`entry-${index}.txt`, 'x']);
await assert.rejects(readPromtgenPackage(await maliciousPackage(JSON.stringify(result.project), tooManyEntries)), /500 girdi sınırını/);
await assert.rejects(readPromtgenPackage(await maliciousPackage(JSON.stringify(result.project), [['oversized.txt', 'x'.repeat(5 * 1024 * 1024 + 1)]])), /girdisi çok büyük/);
const inflatedEntries = Array.from({ length: 11 }, (_, index) => [`inflated-${index}.txt`, 'z'.repeat(5 * 1024 * 1024)]);
await assert.rejects(readPromtgenPackage(await maliciousPackage(JSON.stringify(result.project), inflatedEntries)), /açılmış içerik boyutu/);
assert.equal(redactSensitiveText('api_key=super-secret-value'), 'api_key=[REDACTED]');
console.log('✓ V4 migration and canonical exports');
