export const UNIVERSAL_PHASES = {
    IDEA_CAPTURED: 'IDEA_CAPTURED',
    PROJECT_PROFILED: 'PROJECT_PROFILED',
    DISCOVERY_IN_PROGRESS: 'DISCOVERY_IN_PROGRESS',
    OBJECTIVES_DEFINED: 'OBJECTIVES_DEFINED',
    SCOPE_DEFINED: 'SCOPE_DEFINED',
    DELIVERABLES_DEFINED: 'DELIVERABLES_DEFINED',
    EXECUTION_PLAN_DRAFTED: 'EXECUTION_PLAN_DRAFTED',
    REVIEW_IN_PROGRESS: 'REVIEW_IN_PROGRESS',
    READY_FOR_EXPORT: 'READY_FOR_EXPORT',
    EXPORTED: 'EXPORTED'
};

export const UNIVERSAL_PHASE_METADATA = {
    [UNIVERSAL_PHASES.IDEA_CAPTURED]: { label: 'Fikir Girişi', index: 0 },
    [UNIVERSAL_PHASES.PROJECT_PROFILED]: { label: 'Profil Çıkarma', index: 1 },
    [UNIVERSAL_PHASES.DISCOVERY_IN_PROGRESS]: { label: 'Keşif ve Sorular', index: 2 },
    [UNIVERSAL_PHASES.OBJECTIVES_DEFINED]: { label: 'Hedefler', index: 3 },
    [UNIVERSAL_PHASES.SCOPE_DEFINED]: { label: 'Kapsam', index: 4 },
    [UNIVERSAL_PHASES.DELIVERABLES_DEFINED]: { label: 'Çıktılar', index: 5 },
    [UNIVERSAL_PHASES.EXECUTION_PLAN_DRAFTED]: { label: 'Uygulama Planı', index: 6 },
    [UNIVERSAL_PHASES.REVIEW_IN_PROGRESS]: { label: 'Kalite Gözden Geçirme', index: 7 },
    [UNIVERSAL_PHASES.READY_FOR_EXPORT]: { label: 'Hazır', index: 8 },
    [UNIVERSAL_PHASES.EXPORTED]: { label: 'İndirildi', index: 9 }
};

export const PHASE_APPROVAL_KEYS = {};
for (const phase of Object.values(UNIVERSAL_PHASES)) {
    PHASE_APPROVAL_KEYS[phase] = null;
}
PHASE_APPROVAL_KEYS[UNIVERSAL_PHASES.PROJECT_PROFILED] = 'profile';
PHASE_APPROVAL_KEYS[UNIVERSAL_PHASES.OBJECTIVES_DEFINED] = 'objectives';
PHASE_APPROVAL_KEYS[UNIVERSAL_PHASES.SCOPE_DEFINED] = 'scope';
PHASE_APPROVAL_KEYS[UNIVERSAL_PHASES.DELIVERABLES_DEFINED] = 'deliverables';
PHASE_APPROVAL_KEYS[UNIVERSAL_PHASES.EXECUTION_PLAN_DRAFTED] = 'executionPlan';
PHASE_APPROVAL_KEYS[UNIVERSAL_PHASES.READY_FOR_EXPORT] = 'finalReview';

export const PHASE_NEXT = {
    [UNIVERSAL_PHASES.IDEA_CAPTURED]: UNIVERSAL_PHASES.PROJECT_PROFILED,
    [UNIVERSAL_PHASES.PROJECT_PROFILED]: UNIVERSAL_PHASES.DISCOVERY_IN_PROGRESS,
    [UNIVERSAL_PHASES.DISCOVERY_IN_PROGRESS]: UNIVERSAL_PHASES.OBJECTIVES_DEFINED,
    [UNIVERSAL_PHASES.OBJECTIVES_DEFINED]: UNIVERSAL_PHASES.SCOPE_DEFINED,
    [UNIVERSAL_PHASES.SCOPE_DEFINED]: UNIVERSAL_PHASES.DELIVERABLES_DEFINED,
    [UNIVERSAL_PHASES.DELIVERABLES_DEFINED]: UNIVERSAL_PHASES.EXECUTION_PLAN_DRAFTED,
    [UNIVERSAL_PHASES.EXECUTION_PLAN_DRAFTED]: UNIVERSAL_PHASES.REVIEW_IN_PROGRESS,
    [UNIVERSAL_PHASES.REVIEW_IN_PROGRESS]: UNIVERSAL_PHASES.READY_FOR_EXPORT,
    [UNIVERSAL_PHASES.READY_FOR_EXPORT]: UNIVERSAL_PHASES.EXPORTED,
    [UNIVERSAL_PHASES.EXPORTED]: null
};
