// Generated by `npm run comparison:benchmark`; do not edit manually.
export const COMPARISON_EVIDENCE: {
  studyId: string;
  reportPath: string;
  generatedAt: string;
  publicationEligible: boolean;
  userParticipantsByCapability: Record<string, number>;
} = Object.freeze({
  "studyId": "promtgen-comparison-v1",
  "reportPath": "benchmarks/comparison/latest-report.json",
  "generatedAt": "2026-08-16T14:33:27.844Z",
  "publicationEligible": false,
  "userParticipantsByCapability": {}
});
